### ISSUE TITLE
[PE-D][Tester C] Documentation Bug User Guide for Edit Command (Remark Field)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-4/tp#171]
![image.png](https://raw.githubusercontent.com/nigellqx/ped/main/files/11ea9354-9874-4a0b-bce0-93aa324df234.png)
The command did not show the user that they can edit the remark field (the [-r REMARK] is missing)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: nigellqx/ped#2

**Comment by anselmlong** [comment]
oki
