### ISSUE TITLE
[PE-D][Tester D] Duplicate emails are allowed

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-4/tp#174]
![image.png](https://raw.githubusercontent.com/yooplo/ped/main/files/c490eb08-28ef-4865-8ea4-6334f2c5abad.png)

Different clients should not have the same email address

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: yooplo/ped#6

**Comment by anselmlong** [comment]
We will allow duplicates as the numbers/email could be the company's number. However, we will state this in the User Guide.
