### ISSUE TITLE
[PE-D][Tester C] Documentation Bug User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-4/tp#183]
I think that there is an inconsistent use of [-a ADDRESS] and [-l LOCATION] throughout the UG. I think should just keep to one of them.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: nigellqx/ped#5

**Comment by anselmlong** [comment]
Should be location. Thanks!
