### ISSUE TITLE
[PE-D][Tester D] Export addressbook

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-4/tp#184]
![image.png](https://raw.githubusercontent.com/yooplo/ped/main/files/dc4450f6-2479-4235-910c-e1bcdb1b115f.png)

Would the export window be called "Export VBook" rather than "Export Address Book"

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: yooplo/ped#8

**Comment by anselmlong** [comment]
Fair enough.
