### ISSUE TITLE
[PE-D][Tester C] Documentation Bug DG User Stories

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-4/tp#189]
![image.png](https://raw.githubusercontent.com/nigellqx/ped/main/files/dc68344d-6192-47b6-acd5-9248a594ca82.png)
I think this user stories sounds weird because it is implying that the aim of the edit command is to avoid errors when updating information. Instead, I think it is to rectify the error when the error has already been made. Something like "As a user, I want to be able to edit contact details so that I can rectify errors I made when adding a contact."

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: nigellqx/ped#6

**Comment by anselmlong** [comment]
Okay
