### ISSUE TITLE
[PE-D][Tester C] Missing Implementation of Settings Feature specified in DG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-4/tp#192]
![image.png](https://raw.githubusercontent.com/nigellqx/ped/main/files/2aacd425-2374-473f-ad4a-792e4bd3ed2c.png)
The configuration of keyboard shortcuts is not implemented.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nigellqx/ped#8

**Comment by anselmlong** [comment]
This will be a future enhancement, we will split up user stories into those that are already implemented, versus those that are planned in the future.
