### ISSUE TITLE
[PE-D][Tester C] Missing Implementation of feature specified in user stories

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-4/tp#195]
![image.png](https://raw.githubusercontent.com/nigellqx/ped/main/files/9f68aa0b-9111-4553-af3c-066d6ceb92bd.png)
Missing implementation of the filter feature

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: nigellqx/ped#9

**Comment by anselmlong** [comment]
Duplicate of #192
