### ISSUE TITLE
[PE-D][Tester A] UG: Hyperlinks under Export and FAQ sections don't work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-4/tp#211]
In particular, the hyperlink to **FAQ** under **Export Data** and the hyperlink to **Quick Start** under **FAQ** don't work as expected. Maybe because of wrong markdown hashtag.

![image.png](https://raw.githubusercontent.com/DennieDan/ped/main/files/1e74c086-36d8-4be7-826b-6129de766280.png)

![image.png](https://raw.githubusercontent.com/DennieDan/ped/main/files/0aeb017a-2c50-4863-a237-3fb4488aecc9.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: DennieDan/ped#16

**Comment by anselmlong** [comment]
Good catch.

**Comment by anselmlong** [comment]
Quick Start hyperlink is fixed, but FAQ seems to work. Can someone else try?
