### ISSUE TITLE
[PE-D][Tester A] DG: Hyperlinks under Documentation, logging, testing , configuring navigates to Local Host

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-4/tp#215]
Instead of navigating to the Project Website hosted by GitHub, the links in the DG try to connect to the local host which then leads to an unavailable site.

![image.png](https://raw.githubusercontent.com/DennieDan/ped/main/files/0962c337-2abd-4eb8-b301-8b9aeddbd26a.png)

![image.png](https://raw.githubusercontent.com/DennieDan/ped/main/files/feae55a5-509d-442f-a05f-8bc9cf6eddcb.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: DennieDan/ped#17

**Comment by anselmlong** [comment]
Okay.
